"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _nueva_venta_catalog from './nueva-venta-catalog.bones.json'
import _inventario_page from './inventario-page.bones.json'
import _stock_page from './stock-page.bones.json'
import _empleados_table from './empleados-table.bones.json'
import _proveedores_page from './proveedores-page.bones.json'
import _reportes_page from './reportes-page.bones.json'

registerBones({
  "nueva-venta-catalog": _nueva_venta_catalog,
  "inventario-page": _inventario_page,
  "stock-page": _stock_page,
  "empleados-table": _empleados_table,
  "proveedores-page": _proveedores_page,
  "reportes-page": _reportes_page,
})
